### ISSUE TITLE
Create A Branch for Color-Palette Experimentation

### ISSUE THREAD

**Issue by BrianSipple** [emberjs/design#2]
@MelSumner were discussing this idea recently (and [this issue](https://github.com/ember-a11y/issues/issues/1) is partially related), but it would be handy to put together a page where we can take any color palettes we're experimenting with, toggle one of them on/off, and instantly see how the palette appears across the page ([CSS Zen Garden](http://www.csszengarden.com/) is a good, conceptually similar example).  

(Part of me also wants to kill two birds with one stone and use such a prototype to flesh out ideas around the larger website redesign. So this could be a serendipitous primer for that, as well).

**Comment by wifelette** [comment]
Done!

https://github.com/emberjs/whiteboard/tree/design-color-palette-experimentation

I'm still working on pondering the naming convention for the branches so that if we ever have lots they're easily organized. Haven't worked with Branch Tags before, it could be that's a better answer than prefixes? I'm open to convincing either way, and we can rename as needed as we figure it all out :)
